### PR TITLE
Replace pathfinder1 to pathfinder2 version

### PR DESCRIPTION
**Pull request by JacqueGM**
Update circles-transfer package to the new pathfinder

- [x] Pathfinder2 binary in use: https://github.com/chriseth/pathfinder2/commit/a677c3a9a0ea692abc69ef7095927af7e10da636
- [x] Use the new option `hops`
- [x] Update dependencies in GH actions

### CODE REVIEW

**Comment by JacqueGM** [comment]
current issue: error seems to appear non determiniscally. I removed the methd isPathGiven since I was not sure what it was used for and it throws error sometimes

**Comment by JacqueGM** [comment]
test pass locally but not in actions...

**Comment by llunaCreixent** [comment]
We also have to figure out the a good value for the hops

**Review by llunaCreixent — COMMENTED** [review]
Are we keeping the old pathfinder binary for some reason?

**Comment by llunaCreixent** [comment]
> 

Fixed uploading the linux build of the bin

**Comment by llunaCreixent** [comment]
> test pass locally but not in actions...

Fixed uploading the linux build of the bin

**Review by llunaCreixent — APPROVED** [review]
Fantastic ❤️

**Pull request merged**
